### ISSUE TITLE
where is /run.sh located

### ISSUE THREAD

**Issue by aracloud** [infoslack/docker-dvwa#3]
Hi

I want to understand the code a bit further.
Within the Dockerfile you run /run.sh in the CMD section.
Where is this file stored or from where does the file come from?
I'm new to docker.

Thx

**Comment by infoslack** [comment]
Hey @aracloud , the `run.sh` file is provided by the `tutum/lamp` image.
Basically it starts the services and creates the `user/password` for MySQL.
You can check here: https://github.com/tutumcloud/lamp/blob/master/run.sh
and here: https://github.com/tutumcloud/lamp/tree/master#loading-your-custom-php-application

**Comment by abdullahfasih** [comment]
/tmp/setup_dvwa.sh not found 
I keep getting this issue when ever I run the docker file
![appissue](https://user-images.githubusercontent.com/15173316/62576727-6a8abf00-b86b-11e9-9d72-1f298407c684.PNG)
